<?php

$uri = get_template_directory_uri() . '/liquid/assets/img/demos/';

// Demos

$demos = array(
	'renovation' => array(
		'title'       => esc_html__( 'Renovation', 'archub' ),	
		'description' => '',
		'screenshot'  => $uri . 'renovation.jpeg',
		'preview'     => 'https://renovationarc.liquid-themes.com/',
		'has_widgets' => true,
		'builder'     => 'elementor',
	),
	'adaptive' => array(
		'title'       => esc_html__( 'Adaptive Colours', 'archub' ),	
		'description' => '',
		'screenshot'  => $uri . 'adaptive.jpeg',
		'preview'     => 'https://arcadaptive.liquid-themes.com/',
		'has_widgets' => true,
		'builder'     => 'elementor',
	),
	'modernblocks' => array(
		'title'       => esc_html__( 'Modern Blocks', 'archub' ),	
		'description' => '',
		'screenshot'  => $uri . 'modernblocks.jpeg',
		'preview'     => 'https://modernblocksarc.liquid-themes.com/',
		'has_widgets' => true,
		'builder'     => 'elementor',
	),
	'interior_design2' => array(
		'title'       => esc_html__( 'Interior Design 2', 'archub' ),	
		'description' => '',
		'screenshot'  => $uri . 'interior_design2.jpeg',
		'preview'     => 'https://interiortwoarc.liquid-themes.com/',
		'has_widgets' => true,
		'builder'     => 'elementor',
	),
	'minimalist' => array(
		'title'       => esc_html__( 'Minimalist', 'archub' ),	
		'description' => '',
		'screenshot'  => $uri . 'minimalist.jpeg',
		'preview'     => 'https://minimalistarc.liquid-themes.com/',
		'has_widgets' => true,
		'builder'     => 'elementor',
	),
	'interior' => array(
		'title'       => esc_html__( 'Interior', 'archub' ),	
		'description' => '',
		'screenshot'  => $uri . 'interior.jpeg',
		'preview'     => 'https://interiorarc.liquid-themes.com/',
		'has_widgets' => true,
		'builder'     => 'elementor',
	),
	'dark' => array(
		'title'       => esc_html__( 'Dark', 'archub' ),	
		'description' => '',
		'screenshot'  => $uri . 'dark.jpeg',
		'preview'     => 'https://darkarc.liquid-themes.com/',
		'has_widgets' => true,
		'builder'     => 'elementor',
	),
	'project_slider' => array(
		'title'       => esc_html__( 'Project Slider', 'archub' ),	
		'description' => '',
		'screenshot'  => $uri . 'project_slider.jpeg',
		'preview'     => 'https://projectsliderarc.liquid-themes.com/',
		'has_widgets' => true,
		'builder'     => 'elementor',
	),
	'asymmetric_one' => array(
		'title'       => esc_html__( 'Asymmetric One', 'archub' ),	
		'description' => '',
		'screenshot'  => $uri . 'asymmetric_one.jpeg',
		'preview'     => 'https://asyonearc.liquid-themes.com/',
		'has_widgets' => true,
		'builder'     => 'elementor',
	),
	'architecture_studio' => array(
		'title'       => esc_html__( 'Architecture Studio', 'archub' ),	
		'description' => '',
		'screenshot'  => $uri . 'arc_studio.jpeg',
		'preview'     => 'https://arcstudiotwo.liquid-themes.com/',
		'has_widgets' => true,
		'builder'     => 'elementor',
	),
	'arc_studio' => array(
		'title'       => esc_html__( 'Arc Studio', 'archub' ),	
		'description' => '',
		'screenshot'  => $uri . 'architecture_studio.jpeg',
		'preview'     => 'https://arcstudio.liquid-themes.com/',
		'has_widgets' => true,
		'builder'     => 'elementor',
	),
	'asymmetric_portfolio' => array(
		'title'       => esc_html__( 'Asymmetric Portfolio', 'archub' ),	
		'description' => '',
		'screenshot'  => $uri . 'pageblocks2.jpeg',
		'preview'     => 'https://portfolioarc.liquid-themes.com/',
		'has_widgets' => true,
		'builder'     => 'elementor',
	),
	'portfolio_zigzag' => array(
		'title'       => esc_html__( 'Portfolio ZigZag', 'archub' ),	
		'description' => '',
		'screenshot'  => $uri . 'portfolio_zigzag.jpeg',
		'preview'     => 'https://portfoliozigzagarc.liquid-themes.com/',
		'has_widgets' => true,
		'builder'     => 'elementor',
	),
	'minimal' => array(
		'title'       => esc_html__( 'Minimal', 'archub' ),	
		'description' => '',
		'screenshot'  => $uri . 'minimal.jpeg',
		'preview'     => 'https://minimalarc.liquid-themes.com/',
		'has_widgets' => true,
		'builder'     => 'elementor',
	),
	'residence' => array(
		'title'       => esc_html__( 'Residence', 'archub' ),	
		'description' => '',
		'screenshot'  => $uri . 'residence.jpeg',
		'preview'     => 'https://residencearc.liquid-themes.com/',
		'has_widgets' => true,
		'builder'     => 'elementor',
	),
	'projects_panel' => array(
		'title'       => esc_html__( 'Portfolio Panel', 'archub' ),	
		'description' => '',
		'screenshot'  => $uri . 'projects_panel.jpeg',
		'preview'     => 'https://projectpanelarc.liquid-themes.com/',
		'has_widgets' => true,
		'builder'     => 'elementor',
	),
	'pageblocks2' => array(
		'title'       => esc_html__( 'Page Blocks 2', 'archub' ),	
		'description' => '',
		'screenshot'  => $uri . 'asymmetric_portfolio.jpeg',
		'preview'     => 'https://pageblockstwo.liquid-themes.com/',
		'has_widgets' => true,
		'builder'     => 'elementor',
	),
	'portfolio_boxes' => array(
		'title'       => esc_html__( 'Portfolio Boxes', 'archub' ),	
		'description' => '',
		'screenshot'  => $uri . 'portfolio_boxes.jpeg',
		'preview'     => 'https://portfolioboxes.liquid-themes.com/',
		'has_widgets' => true,
		'builder'     => 'elementor',
	),
	'pageblocks3' => array(
		'title'       => esc_html__( 'Page Blocks 3', 'archub' ),	
		'description' => '',
		'screenshot'  => $uri . 'pageblocks3.jpeg',
		'preview'     => 'https://pageblocksthree.liquid-themes.com/',
		'has_widgets' => true,
		'builder'     => 'elementor',
	),
	'vertical_portfolio' => array(
		'title'       => esc_html__( 'Vertical Portfolio', 'archub' ),	
		'description' => '',
		'screenshot'  => $uri . 'vertical_portfolio.jpeg',
		'preview'     => 'https://verticalportfolioarc.liquid-themes.com/',
		'has_widgets' => true,
		'builder'     => 'elementor',
	),
	'split' => array(
		'title'       => esc_html__( 'Split', 'archub' ),	
		'description' => '',
		'screenshot'  => $uri . 'split.jpeg',
		'preview'     => 'https://splitarc.liquid-themes.com/',
		'has_widgets' => true,
		'builder'     => 'elementor',
	),
	'architect' => array(
		'title'       => esc_html__( 'Architect', 'archub' ),	
		'description' => '',
		'screenshot'  => $uri . 'architect.jpeg',
		'preview'     => 'https://architectarc.liquid-themes.com/',
		'has_widgets' => true,
		'builder'     => 'elementor',
	),
	'parallax' => array(
		'title'       => esc_html__( 'Parallax', 'archub' ),	
		'description' => '',
		'screenshot'  => $uri . 'parallax.jpeg',
		'preview'     => 'https://parallaxarc.liquid-themes.com/',
		'has_widgets' => true,
		'builder'     => 'elementor',
	),
	'freelancer_architect' => array(
		'title'       => esc_html__( 'Freelancer Architect', 'archub' ),	
		'description' => '',
		'screenshot'  => $uri . 'freelancer_architect.jpeg',
		'preview'     => 'https://freelancerarchitectarc.liquid-themes.com/',
		'has_widgets' => true,
		'builder'     => 'elementor',
	),
	'neo_architecture' => array(
		'title'       => esc_html__( 'NeoArc', 'archub' ),	
		'description' => '',
		'screenshot'  => $uri . 'neo_architecture.jpeg',
		'preview'     => 'https://neoarc.liquid-themes.com/',
		'has_widgets' => true,
		'builder'     => 'elementor',
	),
	'arcstudio3' => array(
		'title'       => esc_html__( 'ArcStudio 3', 'archub' ),	
		'description' => '',
		'screenshot'  => $uri . 'architecture_studio3.jpeg',
		'preview'     => 'https://arcstudio3.liquid-themes.com/',
		'has_widgets' => true,
		'builder'     => 'elementor',
	),
	'construction_company' => array(
		'title'       => esc_html__( 'Construction Company', 'archub' ),	
		'description' => '',
		'screenshot'  => $uri . 'construction_company.jpeg',
		'preview'     => 'https://constructioncompanyarc.liquid-themes.com/',
		'has_widgets' => true,
		'builder'     => 'elementor',
	),
	'the_building' => array(
		'title'       => esc_html__( 'The Building', 'archub' ),	
		'description' => '',
		'screenshot'  => $uri . 'building_company.jpeg',
		'preview'     => 'https://thebuildingarc.liquid-themes.com/',
		'has_widgets' => true,
		'builder'     => 'elementor',
	),
	'interior_studio' => array(
		'title'       => esc_html__( 'Interior Studio', 'archub' ),	
		'description' => '',
		'screenshot'  => $uri . 'interior_design_studio.jpeg',
		'preview'     => 'https://interiorstudioarc.liquid-themes.com/',
		'has_widgets' => true,
		'builder'     => 'elementor',
	),
	'vcard' => array(
		'title'       => esc_html__( 'vCard', 'archub' ),	
		'description' => '',
		'screenshot'  => $uri . 'vcard.jpeg',
		'preview'     => 'https://vcardarc.liquid-themes.com/',
		'has_widgets' => true,
		'builder'     => 'elementor',
	),
	'shop' => array(
		'title'       => esc_html__( 'Shop', 'archub' ),	
		'description' => '',
		'screenshot'  => $uri . 'shop.webp',
		'preview'     => 'http://shoparc.liquid-themes.com/',
		'has_widgets' => true,
		'builder'     => 'elementor',
	),
	'construction1' => array(
		'title'       => esc_html__( 'Construction One', 'archub' ),	
		'description' => '',
		'screenshot'  => $uri . 'construction1.webp',
		'preview'     => 'http://constructionone.liquid-themes.com/',
		'has_widgets' => true,
		'builder'     => 'elementor',
	),
	'construction2' => array(
		'title'       => esc_html__( 'Construction Two', 'archub' ),	
		'description' => '',
		'screenshot'  => $uri . 'construction2.webp',
		'preview'     => 'http://constructiontwo.liquid-themes.com/',
		'has_widgets' => true,
		'builder'     => 'elementor',
	),
);