<?php
 $accordion = array(
    'lqdsep-accordion-active-has-fill' => 'elements/accordion/accordion-active-has-fill.css',
    'lqdsep-accordion-active-has-shadow' => 'elements/accordion/accordion-active-has-shadow.css',
    'lqdsep-accordion-base' => 'elements/accordion/accordion-base.css',
    'lqdsep-accordion-body-bordered' => 'elements/accordion/accordion-body-bordered.css',
    'lqdsep-accordion-body-round' => 'elements/accordion/accordion-body-round.css',
    'lqdsep-accordion-body-shadow' => 'elements/accordion/accordion-body-shadow.css',
    'lqdsep-accordion-body-underlined' => 'elements/accordion/accordion-body-underlined.css',
    'lqdsep-accordion-content-has-fill' => 'elements/accordion/accordion-content-has-fill.css',
    'lqdsep-accordion-expander' => 'elements/accordion/accordion-expander.css',
    'lqdsep-accordion-heading-has-shadow' => 'elements/accordion/accordion-heading-has-shadow.css',
    'lqdsep-accordion-lg' => 'elements/accordion/accordion-lg.css',
    'lqdsep-accordion-side-spacing' => 'elements/accordion/accordion-side-spacing.css',
    'lqdsep-accordion-sm' => 'elements/accordion/accordion-sm.css',
    'lqdsep-accordion-title-bg-transparent' => 'elements/accordion/accordion-title-bg-transparent.css',
    'lqdsep-accordion-title-bordered' => 'elements/accordion/accordion-title-bordered.css',
    'lqdsep-accordion-title-circle' => 'elements/accordion/accordion-title-circle.css',
    'lqdsep-accordion-title-round' => 'elements/accordion/accordion-title-round.css',
    'lqdsep-accordion-title-underlined' => 'elements/accordion/accordion-title-underlined.css',
    'lqdsep-accordion-xs' => 'elements/accordion/accordion-xs.css',
);