<?php
 $contact_form = array(
    'lqdsep-contact-form-base' => 'elements/contact-form/contact-form-base.css',
    'lqdsep-contact-form-button-border-none' => 'elements/contact-form/contact-form-button-border-none.css',
    'lqdsep-contact-form-button-border-thin' => 'elements/contact-form/contact-form-button-border-thin.css',
    'lqdsep-contact-form-button-border-thick' => 'elements/contact-form/contact-form-button-border-thick.css',
    'lqdsep-contact-form-button-border-thicker' => 'elements/contact-form/contact-form-button-border-thicker.css',
    'lqdsep-contact-form-button-fill-underlined' => 'elements/contact-form/contact-form-button-fill-underlined.css',
    'lqdsep-contact-form-button-roundness-round' => 'elements/contact-form/contact-form-button-roundness-round.css',
    'lqdsep-contact-form-button-roundness-circle' => 'elements/contact-form/contact-form-button-roundness-circle.css',
    'lqdsep-contact-form-button-size-sm' => 'elements/contact-form/contact-form-button-size-sm.css',
    'lqdsep-contact-form-button-size-md' => 'elements/contact-form/contact-form-button-size-md.css',
    'lqdsep-contact-form-button-size-lg' => 'elements/contact-form/contact-form-button-size-lg.css',
    'lqdsep-contact-form-button-width-block' => 'elements/contact-form/contact-form-button-width-block.css',
    'lqdsep-contact-form-inputs-border-none' => 'elements/contact-form/contact-form-inputs-border-none.css',
    'lqdsep-contact-form-inputs-border-thin' => 'elements/contact-form/contact-form-inputs-border-thin.css',
    'lqdsep-contact-form-inputs-border-thick' => 'elements/contact-form/contact-form-inputs-border-thick.css',
    'lqdsep-contact-form-inputs-border-thicker' => 'elements/contact-form/contact-form-inputs-border-thicker.css',
    'lqdsep-contact-form-inputs-fill-filled' => 'elements/contact-form/contact-form-inputs-fill-filled.css',
    'lqdsep-contact-form-inputs-fill-underlined' => 'elements/contact-form/contact-form-inputs-fill-underlined.css',
    'lqdsep-contact-form-inputs-roundness-sharp' => 'elements/contact-form/contact-form-inputs-roundness-sharp.css',
    'lqdsep-contact-form-inputs-roundness-round' => 'elements/contact-form/contact-form-inputs-roundness-round.css',
    'lqdsep-contact-form-inputs-roundness-circle' => 'elements/contact-form/contact-form-inputs-roundness-circle.css',
    'lqdsep-contact-form-inputs-size-sm' => 'elements/contact-form/contact-form-inputs-size-sm.css',
    'lqdsep-contact-form-inputs-size-md' => 'elements/contact-form/contact-form-inputs-size-md.css',
    'lqdsep-contact-form-inputs-size-lg' => 'elements/contact-form/contact-form-inputs-size-lg.css',
);