<?php
 $custom_menu = array(
    'lqdsep-custom-menu-base' => 'elements/custom-menu/custom-menu-base.css',
    'lqdsep-custom-menu-dropdown-btn-has-fill' => 'elements/custom-menu/custom-menu-dropdown-btn-has-fill.css',
    'lqdsep-custom-menu-dropdown-btn' => 'elements/custom-menu/custom-menu-dropdown-btn.css',
    'lqdsep-custom-menu-dropdown' => 'elements/custom-menu/custom-menu-dropdown.css',
    'lqdsep-custom-menu-icon-base' => 'elements/custom-menu/custom-menu-icon-base.css',
    'lqdsep-custom-menu-icon-right' => 'elements/custom-menu/custom-menu-icon-right.css',
    'lqdsep-custom-menu-items-has-border-inline' => 'elements/custom-menu/custom-menu-items-has-border-inline.css',
    'lqdsep-custom-menu-items-has-border' => 'elements/custom-menu/custom-menu-items-has-border.css',
    'lqdsep-custom-menu-items-has-fill' => 'elements/custom-menu/custom-menu-items-has-fill.css',
    'lqdsep-custom-menu-mobile-collapsible' => 'elements/custom-menu/custom-menu-mobile-collapsible.css',
    'lqdsep-custom-menu-pin' => 'elements/custom-menu/custom-menu-pin.css',
    'lqdsep-custom-menu-sticky-floating-expand' => 'elements/custom-menu/custom-menu-sticky-floating-expand.css',
    'lqdsep-custom-menu-sticky-floating' => 'elements/custom-menu/custom-menu-sticky-floating.css',
    'lqdsep-custom-menu-sticky-floating-vertical' => 'elements/custom-menu/custom-menu-sticky-floating-vertical.css',
    'lqdsep-custom-menu-sticky-indc' => 'elements/custom-menu/custom-menu-sticky-indc.css',
    'lqdsep-custom-menu-sticky-inline' => 'elements/custom-menu/custom-menu-sticky-inline.css',
    'lqdsep-custom-menu-sticky-inline-expand' => 'elements/custom-menu/custom-menu-sticky-inline-expand.css',
    'lqdsep-custom-menu-inline-expand' => 'elements/custom-menu/custom-menu-inline-expand.css',
    'lqdsep-custom-menu-inline' => 'elements/custom-menu/custom-menu-inline.css',
    'lqdsep-custom-menu-sticky' => 'elements/custom-menu/custom-menu-sticky.css',
    'lqdsep-custom-menu-toggle-has-fill' => 'elements/custom-menu/custom-menu-toggle-has-fill.css',
    'lqdsep-custom-menu-underline' => 'elements/custom-menu/custom-menu-underline.css',
);