<?php
 $fancy_image = array(
    'lqdsep-fancy-image-base' => 'elements/fancy-image/fancy-image-base.css',
    'lqdsep-fancy-image-content-base-reveal' => 'elements/fancy-image/fancy-image-content-base-reveal.css',
    'lqdsep-fancy-image-content-base' => 'elements/fancy-image/fancy-image-content-base.css',
    'lqdsep-fancy-image-content-fixed-base' => 'elements/fancy-image/fancy-image-content-fixed-base.css',
    'lqdsep-fancy-image-content-fixed-left-reveal' => 'elements/fancy-image/fancy-image-content-fixed-left-reveal.css',
    'lqdsep-fancy-image-content-fixed-left' => 'elements/fancy-image/fancy-image-content-fixed-left.css',
    'lqdsep-fancy-image-content-fixed-right-reveal' => 'elements/fancy-image/fancy-image-content-fixed-right-reveal.css',
    'lqdsep-fancy-image-content-fixed-right' => 'elements/fancy-image/fancy-image-content-fixed-right.css',
    'lqdsep-fancy-image-content-overlay-base' => 'elements/fancy-image/fancy-image-content-overlay-base.css',
    'lqdsep-fancy-image-content-overlay-left-reveal' => 'elements/fancy-image/fancy-image-content-overlay-left-reveal.css',
    'lqdsep-fancy-image-content-overlay-right-reveal' => 'elements/fancy-image/fancy-image-content-overlay-right-reveal.css',
    'lqdsep-fancy-image-float-base' => 'elements/fancy-image/fancy-image-float-base.css',
    'lqdsep-fancy-image-float-ease-in-out' => 'elements/fancy-image/fancy-image-float-ease-in-out.css',
    'lqdsep-fancy-image-float-ease-in' => 'elements/fancy-image/fancy-image-float-ease-in.css',
    'lqdsep-fancy-image-shadow-1' => 'elements/fancy-image/fancy-image-shadow-1.css',
    'lqdsep-fancy-image-shadow-2' => 'elements/fancy-image/fancy-image-shadow-2.css',
    'lqdsep-fancy-image-shadow-3' => 'elements/fancy-image/fancy-image-shadow-3.css',
    'lqdsep-fancy-image-shadow-4' => 'elements/fancy-image/fancy-image-shadow-4.css',
    'lqdsep-fancy-image-shadow-animate-1' => 'elements/fancy-image/fancy-image-shadow-animate-1.css',
    'lqdsep-fancy-image-shadow-animate-2' => 'elements/fancy-image/fancy-image-shadow-animate-2.css',
    'lqdsep-fancy-image-shadow-animate-3' => 'elements/fancy-image/fancy-image-shadow-animate-3.css',
    'lqdsep-fancy-image-shadow-animate-4' => 'elements/fancy-image/fancy-image-shadow-animate-4.css',
    'lqdsep-fancy-image-shadow-animate-base' => 'elements/fancy-image/fancy-image-shadow-animate-base.css',
);